e = input('Digite alguma coisa: ')

print(type(e))
print('isalnum? {}'.format(e.isalnum()))
print('isalpha? {}'.format(e.isalpha()))
print('isascii? {}'.format(e.isascii()))
print('isdigit? {}'.format(e.isdigit()))
print('islower? {}'.format(e.islower()))
print('isdecimal? {}'.format(e.isdecimal()))
print('isidentifier? {}'.format(e.isidentifier()))
print('isnumeric? {}'.format(e.isnumeric()))
print('isprintable? {}'.format(e.isprintable()))
print('isspace? {}'.format(e.isspace()))
print('istitle? {}'.format(e.istitle()))
print('isupper? {}'.format(e.isupper()))
